### ISSUE TITLE
Redis和es的设置，应该怎么整呢

### ISSUE THREAD

**Issue by yaowanglaji** [xiaofeixx/film_font#3]

**Comment by xiaofeixx** [comment]
该项目刚开始学习的时候做的，已经很久没有维护了，redis 是在 yml 中配置的，es 在 config 包下进行配置的

**Comment by yaowanglaji** [comment]
想找一个类似于尚硅谷的谷粒学园的视频网站项目，毕设快到截止日期了，老师说我们这得大改，凉凉

**Comment by xiaofeixx** [comment]
这不是一个可以完整直接使用的项目，所以建议你这边再找找看吧
